dir /data

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

save 900 1
save 300 10
save 60 10000

maxmemory 1gb
maxmemory-policy noeviction

bind 0.0.0.0
protected-mode yes
port 6379
tcp-keepalive 300
timeout 0

loglevel notice

lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes

activedefrag yes

rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command DEBUG ""
rename-command CONFIG ""
rename-command SHUTDOWN ""
rename-command KEYS ""
